.PHONY: tags

GIT_DIRS="env \
memo \
samples \
templates \
libtt \
tools"

TAGS_DIRS="libtt"

MEMO_DIRS="memo \
samples"

BUILD_DIRS="libtt \
samples/cpp \
samples/cpp_lib \
samples/app_cmd \
samples/app_imgui \
samples/mycmake \
tools/imgedit \
tools/imgview"


all: status

graph:
	@for-dir.sh "git graph -3" $(GIT_DIRS)

fetch:
	@for-dir.sh "git fetch" $(GIT_DIRS)

status:
	@for-dir.sh "git status -s" $(GIT_DIRS)

tags:
	@for-dir.sh "make tags" $(TAGS_DIRS)
	@for-dir.sh "make tags.memo" $(MEMO_DIRS)

build:
	@for-dir.sh "make all" $(BUILD_DIRS)

clean:
	@for-dir.sh "make all.clean" $(BUILD_DIRS)

print-build:
	myfind.sh -b

help:
	@echo "make target"
	@echo ""
	@echo "target:"
	@echo "  all    ... status in GIT_DIRS"
	@echo "  graph  ... graph  in GIT_DIRS"
	@echo "  fetch  ... fetch  in GIT_DIRS"
	@echo "  status ... status in GIT_DIRS"
	@echo "  tags   ... tags in TAGS_DIRS and MEMO_DIRS"
	@echo "  build  ... build in BUILD_DIRS"
	@echo "  clean  ... clean in BUILD_DIRS"
	@echo "  print-build ... print build directories"

