all: dot

dot:
	dot.sh

vimdiff:
	dot.sh --vimdiff

vimdirdiff:
	dot.sh --vimdirdiff

dot-win:
	dot.sh $(MY_WIN_HOME)

vimdiff-win:
	dot.sh --vimdiff $(MY_WIN_HOME)

vimdirdiff-win:
	dot.sh --vimdirdiff $(MY_WIN_HOME)

