#!/bin/bash

source $HOME/.hostname
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# bash
HISTCONTROL=ignoreboth
#umask 022

# env variables
export PAGER='less -FRX'
export EDITOR='vim'
#export GIT_PAGER='less'
#export GIT_EDITOR='vim'

#==========================================================================
# alias
#==========================================================================

unalias -a

alias s='source $HOME/.bashrc'

#==========================================================================
# load common files
#==========================================================================

source $CURRENT_DIR/bashrc.common.path
source $CURRENT_DIR/bashrc.common.func
source $CURRENT_DIR/bashrc.common.alias
source $CURRENT_DIR/bashrc.common.colors
source $CURRENT_DIR/bashrc.git

#==========================================================================
# check installed programs
#==========================================================================

#source $CURRENT_DIR/check_lv.sh

#==========================================================================
# load specific files
#==========================================================================

for i in bashrc.os.$MY_OS_NAME bashrc.shell.$MY_SHELL_NAME bashrc.site.$MY_SITE_NAME bashrc.host.$MY_HOST_NAME; do
  if [ -f $CURRENT_DIR/$i ]; then
    source $CURRENT_DIR/$i
  fi
done

#==========================================================================
# setup
#==========================================================================

f_set_core_off
f_set_git_prompt

