#!/bin/bash

#======================================================
# init
#======================================================

source $HOME/.hostname

export BASHRC_CACHED=$HOME/.bashrc_cached
if [ -f $BASHRC_CACHED ]; then
  source $BASHRC_CACHED
fi

# bash
HISTCONTROL=ignoreboth
#umask 022

# env variables
export PAGER='less -FRX'
export EDITOR='vim'
#export GIT_PAGER='less'
#export GIT_EDITOR='vim'

export WWW_HOME="https://tktwr.github.io/memo/"

unalias -a

