#!/bin/bash

source $HOME/.hostname
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# bash
HISTCONTROL=ignoreboth
#umask 022

# env variables
export PAGER='less -FRX'
export EDITOR='vim'
#export GIT_PAGER='less'
#export GIT_EDITOR='vim'

export WWW_HOME="https://tktwr.github.io/memo/"

unalias -a

#======================================================
# load files
#======================================================

files="\
bashrc.colors \
bashrc.path \
bashrc.func \
bashrc.alias \
bashrc.git \
bashrc.os.$MY_OS_NAME \
bashrc.shell.$MY_SHELL_NAME \
bashrc.site.$MY_SITE_NAME \
bashrc.host.$MY_HOST_NAME \
"

for I in $files; do
  if [ -f $CURRENT_DIR/$I ]; then
    f_time_start $I
    source $CURRENT_DIR/$I
    f_time_end $I
  fi
done

#======================================================
# setup
#======================================================

f_set_core_off
f_set_git_prompt

