gui:
  #showIcons: true
  showFileTree: false
  sidePanelWidth: 0.25
  language: 'en'
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
git:
  paging:
    colorArg: always
    pager: delta.sh
  merging:
    args: '--no-ff'
  log:
    order: 'topo-order'
    #order: 'date-order'
    showGraph: 'always'
  branchLogCmd:      'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=oneline {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=oneline --all'
# keybinding:
#   universal:
#     scrollUpMain-alt2: '<c-u>' # main panel scroll up
#     scrollDownMain-alt2: '<c-d>' # main panel scroll down
