#!/bin/bash

export MY_HOST_NAME=myhost
export MY_SITE_NAME=mysite
export MY_SHELL_NAME=$MSYSTEM
export MY_OS_NAME=windows

export CC=clang
export CXX=clang++

if [ -d $SYS_WIN_HOME ]; then
  export MY_HOME=$SYS_WIN_HOME
else
  export MY_HOME=$HOME
fi
